# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04  # used for building the docs - not user's os
  tools:
    python: "3.9"

sphinx:
   configuration: docs/conf.py
#    builder: html
#    fail_on_warning: false

formats:
#    - html
   - pdf

python:
   install:
#     - method: pip
#       path: .
#     - requirements: requirements.txt
    - requirements: docs/requirements.txt
   
